feat: change revoke and assign behavior to turn on/off the trigger
Farfetch/kafka-flow-retry-extensions pull request #90
Opened 2022-07-19 08:20 UTC by martinhonovais

# Description

The revoke partition was stopping all quartz jobs because we were shutting down the quartz. This pull request changed that behavior to just schedule or unschedule the jobs.

Fixes #76 

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Checklist

-   [X] My code follows the style guidelines of this project
-   [X] I have performed a self-review of my own code
-   [X] I have added tests to cover my changes
-   [ ] I have made corresponding changes to the documentation

### Disclaimer

By sending us your contributions, you are agreeing that your contribution is made subject to the terms of our [Contributor Ownership Statement](https://github.com/Farfetch/.github/blob/master/COS.md)

2022-07-21 11:13 UTC, jdromeiro requested changes

2022-07-21 11:13 UTC, jdromeiro commented on src/KafkaFlow.Retry.UnitTests/KafkaFlow.Retry/Durable/Polling/QueueTrackerTests.cs
> +            var mockITriggerProvider1 = new Mock<ITriggerProvider>();
Rename to mockTriggerProvider2, and rename the mockTriggerProvider as mockTriggerProvider1.

Do the same for the queueTracker and queueTracker1.

2022-07-21 11:13 UTC, jdromeiro commented on src/KafkaFlow.Retry.UnitTests/KafkaFlow.Retry/Durable/Polling/QueueTrackerTests.cs
> +        public async Task QueueTracker_Create_Success()
I think we can explain better what we're trying to achieve with this test by setting the name as:
`QueueTracker_ScheduleAndUnscheduleJobs_Success`

2022-07-21 11:13 UTC, jdromeiro commented on src/KafkaFlow.Retry.UnitTests/KafkaFlow.Retry/Durable/Polling/QueueTrackerTests.cs
> +            (
Maybe make it a little easier to understand by re-writting as:
```
 var timeBetweenJobExecutionsWhileJobWasUnscheduled = jobExecutionContexts
                    .Where(x => x.Trigger.Key.Name == "Trigger1")
                    .OrderBy(x => x.FireTimeUtc)
                    .First()
                    .FireTimeUtc
                    -
                jobExecutionContexts
                    .Where(x => x.Trigger.Key.Name == "Trigger")
                    .OrderBy(x => x.FireTimeUtc)
                    .Last()
                    .FireTimeUtc;

            timeBetweenJobExecutionsWhileJobWasUnscheduled.Should().BeGreaterThan(TimeSpan.FromSeconds(15));
```

2022-07-21 11:16 UTC, jdromeiro requested changes

2022-07-21 11:16 UTC, jdromeiro commented on src/KafkaFlow.Retry.UnitTests/KafkaFlow.Retry/Durable/Polling/QueueTrackerCoordinatorTests.cs
>          public void QueueTrackerCoordinator_Shutdown_Success()
rename to Unschedule

2022-07-21 11:16 UTC, jdromeiro commented on src/KafkaFlow.Retry.UnitTests/KafkaFlow.Retry/Durable/Polling/QueueTrackerCoordinatorTests.cs
>              queueTrackerFactory
Rename the test name to Schedule

2022-07-22 14:20 UTC, martinhonovais commented on src/KafkaFlow.Retry/Durable/Polling/QueueTracker.cs
> -                .ConfigureAwait(false)
Done

2022-07-22 14:33 UTC, martinhonovais commented on src/KafkaFlow.Retry/Durable/Polling/QueueTracker.cs
> +                var triggerAlreadyDefined = this.scheduler
This is unneeded code, so we have decided to remove it.

2022-07-22 15:16 UTC, jdromeiro submitted a review, later dismissed

2022-07-22 15:45 UTC, carlosgoias submitted a review, later dismissed

2022-07-22 15:45 UTC, carlosgoias commented on src/KafkaFlow.Retry/Durable/Polling/JobDetailProvider.cs
> +using Quartz;
using inside of namespance

2022-08-03 08:39 UTC, spookylsm approved these changes

2022-08-10 13:51 UTC, sergioamribeiro approved these changes

2022-10-17 14:09 UTC, carlosgoias approved these changes

2022-10-17 14:10 UTC, brunohfgomes approved these changes

2022-10-17 14:44 UTC, merged